#!/bin/sh

install_dir="$4"
terminfo="/usr/share/terminfo"

mkdir -p "$install_dir"
mkdir -p "$terminfo/a"
mkdir -p "$terminfo/d"
mkdir -p "$terminfo/k"
mkdir -p "$terminfo/l"
mkdir -p "$terminfo/n"
mkdir -p "$terminfo/p"
mkdir -p "$terminfo/r"
mkdir -p "$terminfo/s"
mkdir -p "$terminfo/t"
mkdir -p "$terminfo/v"
mkdir -p "$terminfo/x"

cp "$1/payload/lib/libncurses.a" "$install_dir/libncurses.a"
cp "$1/payload/lib/libform.a" "$install_dir/libform.a"
cp "$1/payload/lib/libmenu.a" "$install_dir/libmenu.a"
cp "$1/payload/lib/libpanel.a" "$install_dir/libpanel.a"
cp "$1/payload/lib/libncurses++.a" "$install_dir/libncurses++.a"

cp "$1/payload/bin/clear" "$install_dir/clear"
cp "$1/payload/bin/infocmp" "$install_dir/infocmp"
cp "$1/payload/bin/tabs" "$install_dir/tabs"
cp "$1/payload/bin/tic" "$install_dir/tic"
cp "$1/payload/bin/toe" "$install_dir/toe"
cp "$1/payload/bin/tput" "$install_dir/tput"
cp "$1/payload/bin/tset" "$install_dir/tset"

cp "$1/payload/include/curses.h" "$install_dir/curses.h"
cp "$1/payload/include/term.h" "$install_dir/term.h"
cp "$1/payload/include/panel.h" "$install_dir/panel.h"
cp "$1/payload/include/form.h" "$install_dir/form.h"
cp "$1/payload/include/menu.h" "$install_dir/menu.h"
cp "$1/payload/include/eti.h" "$install_dir/eti.h"
cp "$1/payload/include/unctrl.h" "$install_dir/unctrl.h"
cp "$1/payload/include/termcap.h" "$install_dir/termcap.h"
cp "$1/payload/include/ncurses_dll.h" "$install_dir/ncurses_dll.h"
cp "$1/payload/include/ncurses_cfg.h" "$install_dir/ncurses_cfg.h"
cp "$1/payload/include/ncurses_def.h" "$install_dir/ncurses_def.h"
cp "$1/payload/include/nc_win32.h" "$install_dir/nc_win32.h"
cp "$1/payload/include/mf_common.h" "$install_dir/mf_common.h"
cp "$1/payload/include/hashsize.h" "$install_dir/hashsize.h"
cp "$1/payload/include/parametrized.h" "$install_dir/parametrized.h"
cp "$1/payload/include/config.h" "$install_dir/config.h"

cp "$1/payload/terminfo/a/ansi" "$terminfo/a/ansi"
cp "$1/payload/terminfo/d/dumb" "$terminfo/d/dumb"
cp "$1/payload/terminfo/k/konsole" "$terminfo/k/konsole"
cp "$1/payload/terminfo/l/linux" "$terminfo/l/linux"
cp "$1/payload/terminfo/n/nxterm" "$terminfo/n/nxterm"
cp "$1/payload/terminfo/p/putty" "$terminfo/p/putty"
cp "$1/payload/terminfo/p/putty-256color" "$terminfo/p/putty-256color"
cp "$1/payload/terminfo/r/rxvt" "$terminfo/r/rxvt"
cp "$1/payload/terminfo/r/rxvt-256color" "$terminfo/r/rxvt-256color"
cp "$1/payload/terminfo/r/rxvt-color" "$terminfo/r/rxvt-color"
cp "$1/payload/terminfo/s/screen" "$terminfo/s/screen"
cp "$1/payload/terminfo/s/screen-256color" "$terminfo/s/screen-256color"
cp "$1/payload/terminfo/t/tmux" "$terminfo/t/tmux"
cp "$1/payload/terminfo/t/tmux-256color" "$terminfo/t/tmux-256color"
cp "$1/payload/terminfo/v/vt100" "$terminfo/v/vt100"
cp "$1/payload/terminfo/v/vt100-am" "$terminfo/v/vt100-am"
cp "$1/payload/terminfo/v/vt102" "$terminfo/v/vt102"
cp "$1/payload/terminfo/v/vt200" "$terminfo/v/vt200"
cp "$1/payload/terminfo/v/vt220" "$terminfo/v/vt220"
cp "$1/payload/terminfo/v/vt52" "$terminfo/v/vt52"
cp "$1/payload/terminfo/x/xterm" "$terminfo/x/xterm"
cp "$1/payload/terminfo/x/xterm-256color" "$terminfo/x/xterm-256color"
cp "$1/payload/terminfo/x/xterm-color" "$terminfo/x/xterm-color"
