name = "fastfetch"
version = "2.65.1"
revision = 2
description = "Fast system information utility"
arch = "x86-64"
maintainer = "AnmiTaliDev"
license = "MIT"
homepage = "https://github.com/fastfetch-cli/fastfetch"
depends = []
