name = "fontconfig"
version = "2.15.0"
revision = 1
description = "Library for configuring and customizing font access"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "MIT"
homepage = "https://www.freedesktop.org/wiki/Software/fontconfig"
depends = [
    "/bin/sh",
    "libexpat",
    "musl",
]
