name = "font-cursor-misc"
version = "1.0.4"
revision = 1
description = "X.org misc font"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "Public Domain"
homepage = "https://xorg.freedesktop.org/"
depends = [
    "encodings",
    "font-alias",
    "mkfontscale",
    "fontconfig",
    "util-macros",
]
