name = "binutils"
version = "2.43.1"
revision = 3
description = "Tools necessary to build programs"
arch = "x86-64"
maintainer = "Zennix"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later AND BSD-3-Clause"
homepage = "https://www.gnu.org/software/binutils/"
depends = [
]
