name = "unibilium"
version = "2.1.1"
revision = 1
description = "Terminfo parsing library"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "LGPL-3.0-or-later"
homepage = "https://github.com/neovim/unibilium/"
depends = [
    "musl",
]
