name = "mkfontscale"
version = "1.2.3"
revision = 1
description = "Scalable font index generator for X"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "MIT"
homepage = "https://xorg.freedesktop.org/"
depends = [
    "/bin/sh",
    "musl",
    "zlib",
]
