name = "xkbcomp"
version = "1.5.0"
revision = 1
description = "XKBD keymap compiler"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "MIT"
homepage = "https://xorg.freedesktop.org"
depends = [
    "musl",
]
