name = "libarchive"
version = "3.8.3"
revision = 1
description = "library that can create and read several streaming archive formats"
arch = "x86-64"
maintainer = "Kyronix Project"
license = "BSD-2-Clause AND BSD-3-Clause AND Public-Domain"
homepage = "https://libarchive.org/"
depends = [
]
